#!/usr/bin/env bash
# Writes stack/stack.env (the file docker compose interpolates) and brings up
# Postgres.
#
# stack.env is derived from vps.conf on every run, except for the password:
# that is generated once and then left alone, because rotating it silently
# would orphan every database the apps already wrote to.

source "$ROOT/lib/common.sh"
load_conf "$ROOT"

skip_unless "${INSTALL_POSTGRES:-1}" "postgres" && exit 0

need_cmd docker "stage 10 should have installed it"

STACK="$ROOT/stack"
ENV_FILE="$STACK/stack.env"

# --- password ---------------------------------------------------------------
PW="${POSTGRES_PASSWORD:-}"
if [[ -z "$PW" ]]; then
    PW="$(read_env "$ENV_FILE" POSTGRES_PASSWORD || true)"
fi
if [[ -z "$PW" ]]; then
    PW="$(random_secret)"
    info "generated a new postgres password"
else
    log "reusing the existing postgres password"
fi

# --- stack.env --------------------------------------------------------------
# Compose reads this via --env-file. It holds one real secret, so it is 600 and
# gitignored.
umask 077
cat > "$ENV_FILE" <<CONF
# Generated by install/60-postgres.sh from vps.conf — edit vps.conf, not this.
# Contains the Postgres password. Never commit it.
SRV_ROOT=$SRV_ROOT
REPOS_DIR=$REPOS_DIR
DATA_DIR=$DATA_DIR

POSTGRES_VERSION=${POSTGRES_VERSION:-17}
POSTGRES_USER=${POSTGRES_USER:-vpsplus}
POSTGRES_PASSWORD=$PW
POSTGRES_DATABASES=${POSTGRES_DATABASES:-}

PORT_POSTGRES=${PORT_POSTGRES:-5432}
PORT_PLUS=${PORT_PLUS:-3000}
PORT_STUDIO=${PORT_STUDIO:-8787}
PORT_TRILUX=${PORT_TRILUX:-8080}
PORT_NALAR=${PORT_NALAR:-3001}
CONF
chown "$DEPLOY_USER:$DEPLOY_USER" "$ENV_FILE"
chmod 600 "$ENV_FILE"
umask 022
ok "wrote stack/stack.env"

chmod +x "$STACK/postgres/init/"*.sh 2>/dev/null || true

# --- up ---------------------------------------------------------------------
info "starting postgres ${POSTGRES_VERSION:-17}"
docker compose --env-file "$ENV_FILE" -f "$STACK/docker-compose.yml" \
    --profile db up -d postgres

info "waiting for the cluster to accept connections"
for i in $(seq 1 30); do
    if docker exec vpsplus-postgres pg_isready -U "${POSTGRES_USER:-vpsplus}" -d postgres >/dev/null 2>&1; then
        ok "postgres is ready (after ${i}s)"
        break
    fi
    if [[ $i -eq 30 ]]; then die "postgres did not become ready — docker logs vpsplus-postgres"; fi
    sleep 1
done

# The init script only runs on a brand-new volume. On an existing one, create
# any database that is in vps.conf but not yet in the cluster.
for db in ${POSTGRES_DATABASES:-}; do
    if docker exec vpsplus-postgres psql -U "${POSTGRES_USER:-vpsplus}" -d postgres \
        -tAc "SELECT 1 FROM pg_database WHERE datname='$db'" | grep -q 1; then
        log "database exists: $db"
    else
        docker exec vpsplus-postgres psql -U "${POSTGRES_USER:-vpsplus}" -d postgres \
            -c "CREATE DATABASE \"$db\" OWNER \"${POSTGRES_USER:-vpsplus}\";" >/dev/null
        docker exec vpsplus-postgres psql -U "${POSTGRES_USER:-vpsplus}" -d "$db" \
            -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;" >/dev/null
        ok "created database: $db"
    fi
done

printf '\n'
log "connection string (from a container on the vpsplus network):"
log "  postgres://${POSTGRES_USER:-vpsplus}:${PW}@postgres:5432/<db>"
log "from your laptop:  ssh -L 5432:127.0.0.1:5432 ${DEPLOY_USER}@<vps-ip>"
